// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[1] = [
  {
    "version": "0.14.3.0",
    "date": "2026-10-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">缺少专辑艺术家时使用艺术家</span>：开启后，当歌曲专辑艺术家缺失时，则自动使用其艺术家作为专辑艺术家",
          "<span class=\"type-new\">选取专辑艺术家数量</span>：当专辑艺术家缺失时，按各艺术家在该专辑歌曲中的出现次数由高到低排序，选取指定数量作为该专辑的艺术家；设置为 0 时，则选取全部艺术家",
          "<span class=\"type-new\">歌曲年份不同时生成多张专辑</span>：开启后，若专辑内歌曲的年份不同，将按年份拆分为多张同名专辑",
          "<span class=\"type-new\">扫描线程数</span>：扫描音乐文件时使用的线程数，数值越大扫描速度越快，但会占用更多 CPU 资源"
        ]
      },
      {
        "type": "plain",
        "html": "<b>需要注意，当调整了扫描线程数外的其他选项后，需要进行一次全量扫描（打开全量扫描开关后再点击开始扫描）以刷新音乐库。</b><br/><br/>"
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">音乐库设置页面</span>：扫描改为按钮，并使用强调前景色",
          "<span class=\"type-opt\">壁纸设置</span>：壁纸设置现已移至独立的设置页面",
          "<span class=\"type-opt\">内存占用</span>：进行了一系列调整，降低了一些内存占用，后续仍将持续进行内存优化"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">当播放页面壁纸类型选择主窗口壁纸后切换到播放页面不显示壁纸</span> 的问题",
          "修复了 <span class=\"type-fix\">Android 版本在专辑/艺术家详情页面切换横竖屏时没有切换布局</span> 的问题",
          "修复了 <span class=\"type-fix\">统计艺术家页面中艺术家行之间过于紧密</span> 的问题",
          "修复了 <span class=\"type-fix\">在 Android 端显示了用于桌面端的最小化到托盘/任务栏标题选项</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.14.0.0",
    "date": "2026-09-23",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">均衡器</span>：新增 10 段均衡器，内置流行、摇滚、电子等 16 种预设，并支持自定义配置。路径：<b>设置 -> 音频音效</b>",
          "<span class=\"type-new\">混响</span>：新增混响设置，内置房间、客厅、浴室等 15 种预设，并支持自定义配置。路径：<b>设置 -> 音频音效</b>",
          "<span class=\"type-new\">歌单导出歌曲文件</span>：歌单右键菜单新增“导出歌曲文件”选项，可将歌单内的所有歌曲文件导出到所选路径（将自动生成以歌单名命名的文件夹）"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">设置页面调整</span>：为所有设置页面添加宽度限制，与 Windows 设置页面保持一致",
          "<span class=\"type-opt\">Android 播放队列</span>：播放队列不再以底部动作条形式展现，而是移入播放页面，可通过右滑切换至播放队列，或点击播放队列按钮打开"
        ]
      }
    ]
  },
  {
    "version": "0.13.2.0",
    "date": "2026-09-11",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">正在播放页面中歌曲封面和歌曲信息可能不显示</span> 的问题",
          "修复了 <span class=\"type-fix\">正在播放页面中歌词行高亮时未垂直居中</span> 的问题",
          "修复了 <span class=\"type-fix\">统计页面中歌曲质量标识（HQ/SQ/HR）可能不显示</span> 的问题",
          "修复了 <span class=\"type-fix\">当艺术家或专辑艺术家只有一位时，点击艺术家不会关闭播放页面</span> 的问题",
          "修复了 <span class=\"type-fix\">跳转至专辑详情或艺术家详情页面后，无法通过点击左侧专辑或艺术家菜单返回列表页</span> 的问题",
          "修复了 <span class=\"type-fix\">点击歌词后播放页面跟随鼠标移动</span> 的问题",
          "修复了 <span class=\"type-fix\">桌面歌词功能失效</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.13.0.0",
    "date": "2026-09-08",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">睡眠定时</span>：新增睡眠定时功能，可设定倒计时时长，时间到达后自动暂停播放。路径：<b>右下角“...”按钮 -> 睡眠定时</b>",
          "<span class=\"type-new\">频谱刷新间隔</span>：新增频谱刷新间隔设置选项，可自由调整刷新间隔（范围为 10–64 毫秒），原有的“刷新速度”选项已被移除"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">播放进度条</span>：播放进度条现已采用圆角设计",
          "<span class=\"type-opt\">性能提升</span>：Avalonia 升级至 12.1.2，带来更好的性能表现"
        ]
      }
    ]
  },
  {
    "version": "0.12.10.0",
    "date": "2026-07-28",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">专辑详情</span>：专辑详情页面中的歌曲不再显示歌曲封面",
          "<span class=\"type-opt\">音量调节</span>：音量调节弹窗现已支持鼠标滚轮操作。将鼠标悬停在弹窗上滚动滚轮即可调节音量"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">在频谱设置页面关闭频谱时应用可能崩溃</span> 的问题",
          "修复了 <span class=\"type-fix\">专辑详情页面在包含多张CD时歌曲列表显示混乱</span> 的问题",
          "修复了 <span class=\"type-fix\">多个设置页面中滑动条拖拽时抖动</span> 的问题",
          "修复了 <span class=\"type-fix\">播放队列弹框中“添加到歌单”按钮不显示</span> 的问题",
          "修复了 <span class=\"type-fix\">播放页面背景设置为动态渐变后切换至播放页面时短暂白屏再变为渐变</span> 的问题",
          "修复了 <span class=\"type-fix\">播放页面中宽幅封面图片显示尺寸不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">在专辑列表页面删除专辑后页面上方标题右侧计数未更新</span> 的问题",
          "修复了 <span class=\"type-fix\">跳转栏中部分字符可能无法正常点击</span> 的问题"
        ]
      }
    ]
  }
];
