// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[6] = [
  {
    "version": "0.5.4.0",
    "date": "2026-05-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">专辑合并规则</span>：合并专辑前，会检测歌曲之间是否存在碟号或曲目号冲突。若存在冲突，将自动拆分为多张独立专辑",
          "<span class=\"type-opt\">专辑 / 艺术家默认排序</span>：默认排序规则已调整为按名称升序排列",
          "<span class=\"type-opt\">新增艺术家页面显示参与创作艺术家开关</span>：控制是否在艺术家页面显示参与创作的艺术家。默认不显示，可在 <b>设置</b> -> <b>用户界面</b> 中找到 <b>在艺术家页面中显示参与创作艺术家</b> 选项以启用",
          "<span class=\"type-opt\">扫描后自动清理</span>：扫描完成后，没有歌曲的专辑、以及无关的艺术家将被自动删除。若对专辑进行过编辑（如修改年份、封面、专辑艺术家等），则该专辑将保留；艺术家同理",
          "<span class=\"type-opt\">导航菜单设置调整</span>：导航菜单设置已移入独立设置界面，路径：<b>设置</b> -> <b>导航菜单</b>"
        ]
      }
    ]
  },
  {
    "version": "0.5.1.0",
    "date": "2026-05-11",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">播放界面动态渐变壁纸</span>：现在可以为播放界面设置动态渐变壁纸，可在 <b>设置</b> → <b>用户界面</b> → <b>播放界面</b> 中找到 <b>壁纸</b> 选项并进行设置"
        ]
      },
      {
        "type": "opt",
        "items": [
          "对<span class=\"type-opt\">桌面歌词</span>功能进行了多项优化，改善了稳定性和显示效果",
          "<span class=\"type-opt\">侧边栏中统计菜单的图标</span>已更新"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">向播放队列添加歌曲时，弹出的提示中歌曲数量显示为 0</span> 的问题",
          "修复了 <span class=\"type-fix\">播放界面中封面图片外层视觉效果被意外裁剪</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.4.0.0",
    "date": "2026-05-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">歌曲页面文件夹拖拽支持</span>：现在可以直接从文件资源管理器中拖拽包含歌曲的文件夹到歌曲页面，文件夹将被添加并自动开始扫描歌曲",
          "<span class=\"type-new\">扫描进度对话框</span>：扫描进度现在以独立的对话框形式展示"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">播放队列面板右上角按钮间距过大</span> 的问题",
          "修复了 <span class=\"type-fix\">英文环境下“图片圆角强度”选项的文本和描述不显示</span> 的问题",
          "修复了 <span class=\"type-fix\">切换语言后插件管理页面及其设置页面上的文本没有同步切换</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.3.4.0",
    "date": "2026-05-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">当歌曲封面是灰度图像时，颜色提取结果不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">统计页面中的时段统计图表纵坐标文本可能重叠</span> 的问题",
          "修复了 <span class=\"type-fix\">时段统计中的小时记录不正确</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.3.2.0",
    "date": "2026-05-05",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "优化了 <span class=\"type-opt\">歌曲封面颜色提取算法</span>，颜色提取结果更精准",
          "<span class=\"type-opt\">支持将已在队列中的歌曲设为\"下一首\"</span>，队列位置将自动调整"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">krc 和 qrc 格式的歌词文件无法正常加载解析</span> 的问题"
        ]
      }
    ]
  }
];
