// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[2] = [
  {
    "version": "0.12.5.0",
    "date": "2026-07-08",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">播放队列弹出层第二次打开时显示异常</span> 的问题",
          "修复了 <span class=\"type-fix\">歌单页面和播放队列弹出层中列表项无法拖拽</span> 的问题",
          "修复了 <span class=\"type-fix\">歌曲、专辑和艺术家等多个页面中多选功能失效</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.12.3.0",
    "date": "2026-07-06",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">高级设置页面</span>：新增“高级设置”页面，原有的垃圾回收选项已迁移至此页面，并新增“切换页面时触发垃圾回收”选项。路径：<b>设置 -> 高级设置</b>"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">文本调整</span>：移除部分文本中不必要的代词，使表述更加简洁"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">启动后首次切换到专辑/艺术家页面时视图切换按钮图标可能显示不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">在某些情况下动态频谱显示异常</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.12.2.0",
    "date": "2026-07-01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">跳转栏不透明度</span>：新增跳转栏不透明度设置项（适配浅色/深色主题），路径：<b>设置 -> 用户界面 -> 跳转栏叠加层不透明度</b>"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">跳转栏</span>：移除了边框；跳转时目标字符对应的首个条目将默认显示在列表顶部",
          "<span class=\"type-opt\">列表滚动</span>：提升了列表滚动的流畅度"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">跳转栏在窗口尺寸较小时被裁剪</span> 的问题",
          "修复了 <span class=\"type-fix\">跳转栏在某些情况下跳转位置不符合预期</span> 的问题",
          "修复了 <span class=\"type-fix\">CUE 文件内容未发生变化时扫描仍会产生更新</span> 的问题",
          "修复了 <span class=\"type-fix\">Windows 下在任务栏上关闭主窗口时应用没有退出</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.12.0.0",
    "date": "2026-06-27",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">跳转栏</span>：歌曲、专辑和艺术家页面左侧新增字符跳转栏。点击任意字符，列表将自动滚动到该字母开头的歌曲所在位置。<b>注意：该面板只在排序选项中的第一条件为“标题”或“名称”时显示</b>",
          "<span class=\"type-new\">动态渐变背景颜色过渡</span>：为动态渐变背景增加了颜色过渡动画效果"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">俄语文本改进</span>：由 <b>@DanRug08 (MAYHEM)</b> 贡献，非常感谢"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">退出应用时进程未能正常结束</span> 的问题",
          "修复了 <span class=\"type-fix\">切换窗口时歌曲封面出现闪烁</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.11.2.0",
    "date": "2026-06-22",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">单曲循环模式偶发中断</span> 的问题",
          "修复了 <span class=\"type-fix\">Steam 插件文本在某些语言环境下显示异常</span> 的问题",
          "修复了 <span class=\"type-fix\">Windows 版本启动后从迷你窗口切换至主窗口时任务栏缩略图按钮未能正常显示</span> 的问题"
        ]
      }
    ]
  }
];
