// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_META = {
  "totalVersions": 35,
  "pageSize": 5,
  "totalPages": 7
};

window.TYPE_LABELS = {
  "new": "✨ 新增功能",
  "opt": "⚡ 优化调整",
  "fix": "🔧 问题修复",
  "other": "📌 其它"
};

window.CHANGELOG_LABELS = {
  "newFeatures": "✨ 新增功能",
  "improvements": "⚡ 优化调整",
  "bugFixes": "🔧 问题修复",
  "changelogTitle": "更新日志",
  "changelogDesc": "记录轻灵音乐的每一次迭代",
  "prevPage": "上一页",
  "nextPage": "下一页",
  "loading": "加载中…",
  "loadError": "加载失败，点击重试"
};
