// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[5] = [
  {
    "version": "0.6.0.0",
    "date": "2026-05-16",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "other",
        "items": [
          "启用 AOT（预先编译），<span class=\"type-opt\">大幅提升应用性能和启动速度</span>",
          "得益于 AOT，应用体积<span class=\"type-opt\">减小超过 50%</span>"
        ]
      }
    ]
  },
  {
    "version": "0.5.8.0",
    "date": "2026-05-15",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">当设置文件无效时应用无法启动</span> 的问题",
          "修复了 <span class=\"type-fix\">在某些情况下从歌曲封面提取的主色调依然为接近纯白或纯黑色</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.5.7.0",
    "date": "2026-05-14",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">当歌曲封面不是正方形时，下方歌曲信息与封面未对齐</span> 的问题",
          "修复了 <span class=\"type-fix\">空专辑（即没有关联任何歌曲的专辑）无法删除</span> 的问题",
          "修复了 <span class=\"type-fix\">移除指定歌曲时错误移除了其他歌曲</span> 的问题",
          "修复了 <span class=\"type-fix\">当已添加某个文件夹后，再次将该文件夹拖拽到歌曲页面会导致该文件夹被移除</span> 的问题",
          "修复了 <span class=\"type-fix\">移除歌曲后，歌曲页面标题右侧的歌曲数量未及时更新</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.5.6.0",
    "date": "2026-05-13",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "从歌曲封面提取的主色调将<span class=\"type-opt\">自动跳过接近纯黑或纯白的颜色</span>"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">窗口最大化后再切换至全屏时，最大化按钮显示不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">窗口最大化后，左侧导航菜单和右侧滚动条被裁剪</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.5.5.0",
    "date": "2026-05-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">专辑合并规则调整</span>：新增艺术家严格匹配规则。专辑名相同但艺术家不同的歌曲，将不会合并到同一张专辑中"
        ]
      }
    ]
  }
];
