// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[4] = [
  {
    "version": "0.7.8.0",
    "date": "2026-05-21",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">播放采样位深为 16 位的 WAV 文件时崩溃</span> 的问题 （感谢 <b>@FunkeymonkeyTTR</b>）",
          "修复了 <span class=\"type-fix\">部分 M4A 文件时长不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">部分 M4A 文件无法播放</span> 的问题",
          "修复了 <span class=\"type-fix\">统计页面中部分艺术家不显示</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.7.7.0",
    "date": "2026-05-20",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">重采样流程中因缓冲区写入越界而导致的崩溃</span> 的问题 （感谢 <b>@FunkeymonkeyTTR</b>）",
          "修复了 <span class=\"type-fix\">统计页面的歌曲列表中已不存在的歌曲显示错位</span> 的问题",
          "修复了 <span class=\"type-fix\">“添加到下一首”菜单图标显示异常</span> 的问题",
          "修复了 <span class=\"type-fix\">当专辑名或艺术家名包含文件名中不支持的字符时，生成的缩略图无法读取</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.7.4.0",
    "date": "2026-05-19",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">歌曲封面图片现在支持向上查找最多3层父级文件夹</span>：当歌曲所在文件夹中没有封面图片时，将依次向上级目录查找，最多查找3层"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">在搜索页面短时间内多次更改搜索关键词时，可能显示的是上一个关键词的搜索结果</span> 的问题",
          "修复了 <span class=\"type-fix\">在搜索页面输入必定无法搜到结果的关键词时仍然显示了全部歌曲</span> 的问题",
          "修复了 <span class=\"type-fix\">在某些情况下CUE文件解析出的歌曲起始偏移量错误</span> 的问题",
          "修复了 <span class=\"type-fix\">播放 CUE 文件对应的歌曲时，时长显示不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">播放文件夹时，未包含子文件夹中歌曲</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.7.2.0",
    "date": "2026-05-18",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">切换到随机播放模式后，点击任意歌曲时未按预期播放该歌曲</span> 的问题",
          "修复了 <span class=\"type-fix\">因时长读取错误导致 m4a 文件无法添加到曲库</span> 的问题",
          "修复了 <span class=\"type-fix\">底部播放控制面板左侧按钮圆角与歌曲封面缩略图圆角不匹配</span> 的问题",
          "修复了 <span class=\"type-fix\">Steam插件设置无法保存</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.7.0.0",
    "date": "2026-05-17",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">歌曲页面支持拖拽歌曲文件</span>：歌曲页面现已支持文件拖拽操作。可以拖拽一个或多个歌曲文件（或文件夹）到页面中进行扫描，不再限制于文件夹",
          "<span class=\"type-new\">歌单支持拖拽添加歌曲</span>：现在可以直接拖拽一个或多个歌曲文件（或文件夹）到歌单中。拖拽完成后，将自动扫描歌曲并将其添加到歌单"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">动态渐变效果调整</span>：移除了颜色混合，避免出现预期外的颜色",
          "<span class=\"type-opt\">窗口透明效果调整</span>：Windows 11默认选择Mica效果，Windows 10默认选择Acrylic blur效果，其他情况下默认选择Blur效果"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">开源许可页面无法打开</span> 的问题",
          "修复了 <span class=\"type-fix\">当文件后缀为全大写（例如：MP3、FLAC）时，歌曲无法被正常识别</span> 的问题"
        ]
      }
    ]
  }
];
