// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[3] = [
  {
    "version": "0.11.0.0",
    "date": "2026-06-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">任务栏播放控制</span>：鼠标悬停在任务栏图标上时，可进行上一曲、下一曲、播放和暂停操作，播放控制更加便捷",
          "<span class=\"type-new\">歌词编辑</span>：现在可以在歌曲元数据编辑对话框中修改并保存歌曲的内嵌歌词"
        ]
      }
    ]
  },
  {
    "version": "0.10.0.0",
    "date": "2026-06-09",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">UI缩放选项</span>：现在可以调整界面元素的大小。路径：<b>设置 -> 用户界面</b>",
          "<span class=\"type-new\">导航栏展开宽度设置</span>：现在可以调整左侧导航栏展开时的宽度，可调整范围为[100,480]。路径：<b>设置 -> 用户界面</b>",
          "<span class=\"type-new\">新增语言支持</span>：新增繁体中文、英语（英国）、日语、韩语、俄语、德语、法语、葡萄牙语（巴西）、西班牙语、波兰语、土耳其语语言支持。这些语言的文本可能存在错误，欢迎反馈"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">歌词行切换</span>：：添加淡入淡出效果",
          "<span class=\"type-opt\">歌词字体大小和粗细调整</span>普通状态和高亮状态下的歌词文本使用相同的字体大小和粗细"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">专辑编辑对话框中艺术家无法拖拽</span> 的问题",
          "修复了 <span class=\"type-fix\">关闭窗口后再通过任务栏按钮打开窗口之后关闭按钮无法响应</span> 的问题",
          "修复了 <span class=\"type-fix\">当歌曲没有封面时不显示默认图标</span> 的问题",
          "修复了 <span class=\"type-fix\">歌曲末尾被截断</span> 的问题",
          "修复了 <span class=\"type-fix\">播放队列点击歌曲后自动滚动错误导致当前播放歌曲不可见</span> 的问题",
          "修复了 <span class=\"type-fix\">歌曲文件加载失败时仍然显示上一首歌曲封面和歌词</span> 的问题",
          "修复了 <span class=\"type-fix\">保存歌曲元数据时原有歌词丢失</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.9.0.0",
    "date": "2026-06-05",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">歌曲元数据编辑</span>：支持修改歌曲的封面、标题、艺术家和年份等信息。对歌曲元数据的修改默认将同步写入歌曲文件中，需要注意目前不支持编辑来自 CUE 文件的歌曲元数据。路径：右键点击歌曲 -> 选择<b>编辑元数据</b>",
          "<span class=\"type-new\">专辑元数据编辑</span>：支持修改专辑的标题、艺术家和年份等信息。可选择将专辑标题、艺术家、年份和封面同步应用到专辑内的所有歌曲（将同步写入对应的歌曲文件），需要注意当专辑内包含来自 CUE 文件的歌曲时不支持编辑专辑元数据。路径：右键点击专辑 -> 选择<b>编辑元数据</b>",
          "<span class=\"type-new\">全量扫描选项</span>：开启后将重新扫描所有歌曲，以确保歌曲数据为最新状态。路径：<b>设置 -> 音乐库 -> 全量扫描</b>"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">包含文件夹</span>：添加新文件夹时，如果列表中已存在该文件夹的子文件夹，则自动移除这些子文件夹",
          "<span class=\"type-opt\">CUE 文件解析</span>：移除了流派字段中可能附带的双引号",
          "<span class=\"type-opt\">页面跳转</span>：在文件夹页面点击文件夹后，页面指示器将停留在文件夹菜单而非歌曲菜单；歌单页面也做了相应的调整",
          "<span class=\"type-opt\">缩略图生成</span>：统一生成高度为 200 像素的缩略图，不再为歌曲、专辑和艺术家分别生成不同尺寸的缩略图，以减少磁盘空间占用",
          "<span class=\"type-opt\">艺术家/流派解析</span>：智能识别并保留手动修改的歌曲艺术家、专辑艺术家及流派信息，不再被原始标签覆盖"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">添加歌单对话框过小</span> 的问题",
          "修复了 <span class=\"type-fix\">专辑页面右键菜单可能引发崩溃</span> 的问题",
          "修复了 <span class=\"type-fix\">没有歌曲时，点击歌曲页面的<b>曲库</b>按钮跳转后未正确选中<b>设置</b>菜单</span> 的问题",
          "修复了 <span class=\"type-fix\">编辑专辑元数据时，删除艺术家后保存导致该艺术家被错误删除</span> 的问题",
          "修复了 <span class=\"type-fix\">在外部修改歌曲元数据后，重新扫描无法更新歌曲信息</span> 的问题",
          "修复了 <span class=\"type-fix\">在某些情况下，CUE 文件关联的音频文件被意外当作普通歌曲文件添加到曲库</span> 的问题",
          "修复了 <span class=\"type-fix\">已编辑的专辑或艺术家在符合移除条件时仍无法被移除</span> 的问题",
          "修复了 <span class=\"type-fix\">拖拽文件夹或多个歌曲文件到歌曲或歌单页面进行扫描后显示的扫描结果不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">首次切换到专辑页面时视图设置未正确应用</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.8.1.0",
    "date": "2026-05-24",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Mini 窗口播放列表操作</span>：新增 mini 窗口播放列表操作页面，点击右下角的列表按钮即可打开。支持切换歌曲、移除队列中的歌曲、清空队列等操作",
          "<span class=\"type-opt\">Mini 窗口设置</span>：新增 mini 窗口设置页面，点击最右侧的设置按钮即可打开。目前包含以下设置：主题（与全局设置同步）、叠加层透明度，以及是否在任务栏显示 mini 窗口图标",
          "<span class=\"type-opt\">Mini 窗口歌曲封面移除圆角</span>：移除了 mini 窗口中歌曲封面的圆角效果，避免在窗口四角出现黑色或白色区域",
          "<span class=\"type-opt\">时长过滤设置项默认值调整</span>：时长过滤设置项的默认值现已调整为 0，避免影响初次扫描歌曲时的结果"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">专辑详情页面在介绍文本过长时内容溢出</span> 的问题",
          "修复了 <span class=\"type-fix\">艺术家详情页面在介绍文本过长时内容溢出且页面无法滚动</span> 的问题",
          "修复了 <span class=\"type-fix\">艺术家名称包含特殊字符时无法为其设置图片</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.8.0.0",
    "date": "2026-05-22",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">渲染模式选项</span>：当遇到界面闪烁、显示异常等渲染问题时，可尝试切换渲染模式。路径：<b>设置</b> -> <b>用户界面</b> -> <b>渲染模式</b>",
          "<span class=\"type-new\">日志文件自动清除</span>：应用启动时会自动删除 7 天前的日志文件。此外也可以随时在 <b>关于</b> 页面中，点击 <b>日志缓存</b> 下的 <b>清除缓存</b> 以删除所有日志文件"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">设置文件无效时应用无法启动</span> 的问题"
        ]
      }
    ]
  }
];
