// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[7] = [
  {
    "version": "0.3.1.0",
    "date": "2026-05-04",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">统计页面顶部的进度条左侧图标大小已进行调整</span>，界面更加协调"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">日期切换（跨天或跨周）时，“今日”和“本周”的播放时长及播放歌曲数未能正确重置</span> 的问题",
          "修复了 <span class=\"type-fix\">手动设置系统时间时，播放时间统计数据出现异常减少或增加</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.3.0.0",
    "date": "2026-05-03",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">播放控制按钮常驻显示</span>：可通过 <b>设置 -> 用户界面</b> 页面中的 <b>播放控制按钮始终可见</b> 开关启用",
          "<span class=\"type-new\">图片圆角强度独立调节</span>：展开 <b>设置 -> 用户界面</b> 页面中的 <b>图片圆角强度</b> 选项，可分别控制歌曲封面、专辑封面和艺术家图片的圆角程度"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">启动应用时，Steam 丰富状态未按插件中设置的格式正确显示</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.2.1.0",
    "date": "2026-05-02",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "新增 <span class=\"type-new\">专辑列表/专辑详情页删除专辑选项</span>，仅当专辑内无任何歌曲时可用",
          "新增 <span class=\"type-new\">艺术家详情页删除艺术家选项</span>，仅当艺术家没有任何专辑和歌曲时可用"
        ]
      },
      {
        "type": "opt",
        "items": [
          "Steam 插件现为<span class=\"type-opt\">默认启用</span>状态",
          "<span class=\"type-opt\">时长不足 60 秒的歌曲不再计入成就统计</span>——我们希望成就代表真实的听歌习惯"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">因专辑解析流程对碟号/曲目号有严格不重叠要求，导致多张同名专辑且艺术家列表完全相同时启动崩溃</span> 问题（感谢 <b>@FunkeymonkeyTTR</b>）",
          "修复了 <span class=\"type-fix\">被时长过滤规则排除的歌曲，在调整规则后重新扫描也无法入库</span> 问题（感谢 <b>@Nomstuff</b>）",
          "修复了 <span class=\"type-fix\">歌曲的艺术家/专辑艺术家属性可能出现重复同名条目</span> 的问题",
          "修复了 <span class=\"type-fix\">更换专辑或艺术家封面时，旧封面文件残留未清理</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.1.1.0",
    "date": "2026/05/01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "“暂无歌词”提示应用歌曲封面主色"
        ]
      },
      {
        "type": "fix",
        "items": [
          "修复了 <span class=\"type-fix\">托盘菜单播放/暂停按钮状态不正确</span> 的问题",
          "修复了 <span class=\"type-fix\">托盘菜单开启后无法关闭</span> 的问题",
          "修复了 <span class=\"type-fix\">在歌曲点击动作为替换当前队列的情况下点击列表中的歌曲时必定播放第一首歌曲</span> 的问题"
        ]
      }
    ]
  },
  {
    "version": "0.0.1.0",
    "date": "2026/05/01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "plain",
        "html": "轻灵音乐第一个版本。"
      }
    ]
  }
];
