// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[7] = [
  {
    "version": "0.3.1.0",
    "date": "2026-05-04",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Adjusted the icon size on the left side of the progress bar at the top of the stats page</span> for better visual alignment."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">today's and this week's play time and play counts did not reset correctly when crossing a day or week boundary</span>.",
          "Fixed an issue where <span class=\"type-fix\">play time statistics would unexpectedly increase or decrease when manually adjusting the system time</span>."
        ]
      }
    ]
  },
  {
    "version": "0.3.0.0",
    "date": "2026-05-03",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Playback controls can now be always visible</span>. Enable this via the <b>\"Settings -> UI\"</b> page using the <b>\"Play control always visible\"</b> toggle.",
          "<span class=\"type-new\">Added image corner strength control</span>. Expand the <b>\"Image corner strength\"</b> option in <b>\"Settings -> UI\"</b> to independently adjust the corner radius for song covers, album covers, and artist images."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">Steam Rich Presence would not display according to the format set in the Steam plugin when launching the application</span>."
        ]
      }
    ]
  },
  {
    "version": "0.2.1.0",
    "date": "2026-05-02",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "Album list / album details page: <span class=\"type-new\">Added option to delete album</span>，only available when the album contains no songs.",
          "Artist details page <span class=\"type-new\">Added option to delete artist</span>，only available when the artist has no albums and no songs."
        ]
      },
      {
        "type": "opt",
        "items": [
          "Steam plugin is now <span class=\"type-opt\">enabled by default</span>.",
          "<span class=\"type-opt\">Tracks shorter than 60 seconds no longer count toward achievements</span> — we want achievements to represent real listening habits."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed <span class=\"type-fix\">a crash on startup caused by strict disc/track number non-overlap requirements when multiple identical albums with the exact same artist list existed</span>.(thanks to <b>@FunkeymonkeyTTR</b>)",
          "Fixed an issue where <span class=\"type-fix\">tracks excluded by the duration filter could not be re-added after adjusting the filter setting and rescanning</span>.(thanks to <b>@Nomstuff</b>)",
          "Fixed an issue where <span class=\"type-fix\">artist/album artist properties could contain duplicate identical names</span>.",
          "Fixed an issue where <span class=\"type-fix\">old cover files were not deleted when updating album or artist artwork</span>."
        ]
      }
    ]
  },
  {
    "version": "0.1.1.0",
    "date": "2026/05/01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "The \"\"No Lyrics\"\" text now applies track cover's main color."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed <span class=\"type-fix\">incorrect play/pause button state in tray menu</span>.",
          "Fixed an issue where <span class=\"type-fix\">tray menu could not be closed after opening</span>.",
          "Fixed an issue where <span class=\"type-fix\">clicking a song in the list would always play the first song when the action was set to replace the current queue</span>."
        ]
      }
    ]
  },
  {
    "version": "0.0.1.0",
    "date": "2026/05/01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "plain",
        "html": "First version of Ling Player."
      }
    ]
  }
];
