// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[1] = [
  {
    "version": "0.14.3.0",
    "date": "2026-10-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Use artist when album artist is missing</span>: When enabled, if a track's album artist is missing, its artist is automatically used as the album artist",
          "<span class=\"type-new\">Number of album artists to select</span>: When the album artist is missing, artists are ranked by how often they appear on the album's tracks, from most to least frequent, and the specified number are selected as the album's artists. Set to 0 to select all artists",
          "<span class=\"type-new\">Generate multiple albums when tracks have different years</span>: When enabled, if tracks in an album have different years, they are split into multiple albums with the same name by year",
          "<span class=\"type-new\">Scan threads</span>: Number of threads used when scanning music files. Higher values scan faster but use more CPU"
        ]
      },
      {
        "type": "plain",
        "html": "<b>Note that after adjusting options other than scan threads, a full scan is required (enable Full scan and then click Scan Now) to refresh the library.</b><br/><br/>"
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Library settings page</span>: Scan is now a button and uses the accent foreground colour",
          "<span class=\"type-opt\">Wallpaper settings</span>: Wallpaper settings have been moved to a separate settings page",
          "<span class=\"type-opt\">Memory usage</span>: A series of adjustments have been made to reduce some memory usage, and further optimizations will follow"
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the wallpaper was not displayed when switching to the playing page after selecting the main window wallpaper as the playing page wallpaper type</span>.",
          "Fixed an issue where <span class=\"type-fix\">the Android version did not switch layouts when rotating between portrait and landscape on the album/artist details page</span>.",
          "Fixed an issue where <span class=\"type-fix\">artist rows were too tightly spaced on the artist statistics page</span>.",
          "Fixed an issue where <span class=\"type-fix\">desktop-only minimise to tray/taskbar title options were shown on Android</span>."
        ]
      }
    ]
  },
  {
    "version": "0.13.0.0",
    "date": "2026-09-08",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Equalizer</span>: Added a 10-band equalizer with 16 built-in presets including Pop, Rock, and Electronic, along with support for custom configurations. Path: [b]Settings -> Effect[/b].",
          "<span class=\"type-new\">Reverb</span>: Added reverb settings with 15 built-in presets including Room, Living Room, and Bathroom, along with support for custom configurations. Path: [b]Settings -> Effect[/b].",
          "<span class=\"type-new\">Export Tracks from Playlist</span>: Added an \"Export track files\" option to the playlist context menu, allowing all tracks in the playlist to be exported to a selected path (a folder named after the playlist will be created automatically)."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Settings Page Adjustments</span>: Added width limits to all settings pages to align with the Windows settings page.",
          "<span class=\"type-opt\">Android Playing Queue</span>: The playing queue is no longer shown as a Bottom Sheet but has been moved into the playing page. Switch to the playing queue by swiping right, or tap the playing queue button."
        ]
      }
    ]
  },
  {
    "version": "0.13.2.0",
    "date": "2026-09-11",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">track cover art and track info might not be displayed on the now playing page</span>.",
          "Fixed an issue where <span class=\"type-fix\">highlighted lyrics lines were not vertically centered on the now playing page</span>.",
          "Fixed an issue where <span class=\"type-fix\">track quality badges (HQ/SQ/HR) might not be displayed on the statistics page</span>.",
          "Fixed an issue where <span class=\"type-fix\">clicking the artist did not close the playing page when there was only one artist or album artist</span>.",
          "Fixed an issue where <span class=\"type-fix\">after navigating to the album details or artist details page, it was not possible to return to the list page by clicking the album or artist menu on the left</span>.",
          "Fixed an issue where <span class=\"type-fix\">the playing page followed the mouse after clicking on the lyrics</span>.",
          "Fixed an issue where <span class=\"type-fix\">desktop lyrics did not work</span>."
        ]
      }
    ]
  },
  {
    "version": "0.13.0.0",
    "date": "2026-09-08",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Sleep Timer</span>: Added a sleep timer function that automatically pauses playback after a set countdown. Path: <b>Bottom-right \"...\" button -> Sleep Timer</b>.",
          "<span class=\"type-new\">Spectrum Refresh Interval</span>: Added a configurable spectrum refresh interval (range 10–64 ms). The old \"Refresh Speed\" option has been removed."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Playback Progress Bar</span>: The playback progress bar now features rounded corners.",
          "<span class=\"type-opt\">Performance Improvements</span>: Avalonia has been upgraded to 12.1.2, bringing better performance."
        ]
      }
    ]
  },
  {
    "version": "0.12.10.0",
    "date": "2026-07-28",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Album Details</span>: Tracks in the album details page no longer display their cover art.",
          "<span class=\"type-opt\">Volume Adjustment</span>: The volume adjustment popup now supports mouse wheel operation. Hover the mouse over the popup and scroll the wheel to adjust the volume."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed <span class=\"type-fix\">a crash that could occur when closing the spectrum analyzer on the spectrum settings page</span> (<b>Thanks to @MAYHEM</b>).",
          "Fixed an issue where <span class=\"type-fix\">the track list in the album details page displayed incorrectly when the album contained multiple discs</span>.",
          "Fixed an issue where <span class=\"type-fix\">sliders jittered while dragging in several settings pages</span>.",
          "Fixed an issue where <span class=\"type-fix\">the \"Add to Playlist\" button was not shown in the playing queue popup</span>.",
          "Fixed an issue where <span class=\"type-fix\">the playing page would briefly show a white screen before transitioning to the gradient when switching to it with the dynamic gradient background enabled</span>.",
          "Fixed an issue where <span class=\"type-fix\">wide cover images displayed at an incorrect size on the playing page</span>.",
          "Fixed an issue where <span class=\"type-fix\">the count next to the page title did not update after deleting an album from the album list page</span>.",
          "Fixed an issue where <span class=\"type-fix\">certain characters in the jump bar could not be clicked properly."
        ]
      }
    ]
  }
];
