// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[2] = [
  {
    "version": "0.12.5.0",
    "date": "2026-07-08",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the playing queue popup displayed abnormally when opened for the second time</span>.",
          "Fixed an issue where <span class=\"type-fix\">list items in the playlist page and playing queue popup could not be dragged</span>.",
          "Fixed an issue where <span class=\"type-fix\">multi-selection functionality was broken across multiple pages, including tracks, albums, and artists</span>."
        ]
      }
    ]
  },
  {
    "version": "0.12.3.0",
    "date": "2026-07-06",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Advanced Settings Page</span>: Added a new \"Advanced Settings\" page. The existing garbage collection options have been moved here, and a new \"Trigger garbage collection on page switch\" option has been added. Path: <b>Settings -> Advanced Settings</b>."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Text Adjustments</span>: Removed unnecessary pronouns in some UI text for more concise phrasing."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">view toggle button icons might not display correctly when first switching to the album/artist page after startup</span>.",
          "Fixed an issue where <span class=\"type-fix\">the dynamic spectrum displayed abnormally in some cases</span>."
        ]
      }
    ]
  },
  {
    "version": "0.12.2.0",
    "date": "2026-07-01",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Jump Bar Opacity</span>: Added an opacity setting for the jump bar (adapts to light/dark themes). Path: <b>Settings -> UI -> Jump bar overlay opacity</b>."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Jump Bar</span>: Removed the border; when jumping, the first entry corresponding to the target character will now scroll to the top of the list by default.",
          "<span class=\"type-opt\">List Scrolling</span>: Improved the smoothness of list scrolling."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the jump bar was clipped when the window size was too small</span>.",
          "Fixed an issue where <span class=\"type-fix\">the jump bar sometimes navigated to an unexpected position</span>.",
          "Fixed an issue where <span class=\"type-fix\">scanning a CUE file would still trigger an update even when its content had not changed</span>.",
          "Fixed an issue <span class=\"type-fix\">on Windows where the application did not exit when closing the main window via the taskbar</span>."
        ]
      }
    ]
  },
  {
    "version": "0.12.0.0",
    "date": "2026-06-27",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Jump Bar</span>: A character jump bar has been added to the left side of the track, album, and artist pages. Click any character to automatically scroll the list to the first track starting with that letter. <b>Note: This panel is only shown when the primary sorting criterion is set to \"Title\" or \"Name\"</b>.",
          "<span class=\"type-new\">Dynamic Gradient Background Color Transition</span>: Added color transition animation to the dynamic gradient background."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Russian Text Improvements</span>: Contributed by @DanRug08 (MAYHEM), many thanks."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the process did not terminate properly when exiting the application</span>.",
          "Fixed an issue where <span class=\"type-fix\">track covers flickered when switching windows</span>."
        ]
      }
    ]
  },
  {
    "version": "0.11.2.0",
    "date": "2026-06-22",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">single-track repeat mode would occasionally stop working</span>.",
          "Fixed an issue where <span class=\"type-fix\">Steam plugin text displayed incorrectly in certain language environments</span>.",
          "Fixed an issue where <span class=\"type-fix\">taskbar thumbnail buttons were not displayed when switching from mini window to main window after startup on Windows</span>."
        ]
      }
    ]
  }
];
