// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_META = {
  "totalVersions": 35,
  "pageSize": 5,
  "totalPages": 7
};

window.TYPE_LABELS = {
  "new": "✨ New Features",
  "opt": "⚡ Improvements",
  "fix": "🔧 Bug Fixes",
  "other": "📌 Other"
};

window.CHANGELOG_LABELS = {
  "newFeatures": "✨ New Features",
  "improvements": "⚡ Improvements",
  "bugFixes": "🔧 Bug Fixes",
  "changelogTitle": "Changelog",
  "changelogDesc": "Tracking every iteration of Ling Player",
  "prevPage": "Prev",
  "nextPage": "Next",
  "loading": "Loading…",
  "loadError": "Failed to load. Click to retry."
};
