// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[6] = [
  {
    "version": "0.5.4.0",
    "date": "2026-05-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Album Merging Rule</span>: Before merging albums, the player will check for conflicts in disc numbers or track numbers. If conflicts exist, they will be automatically split into separate albums.",
          "<span class=\"type-opt\">Default Sorting for Albums/Artists</span>: The default sorting rule has been adjusted to ascending order by name.",
          "<span class=\"type-opt\">Added \"Show Contributing Artists\" Switch</span>: Control whether to show featured artists on the artist page. Disabled by default. You can find the \"\"Show featured artists on artist page\"\" option in <b>Settings</b> -> <b>UI</b> to enable it.",
          "<span class=\"type-opt\">Auto Cleanup After Scanning</span>: After scanning completes, albums without any tracks and artists without any albums or tracks will be automatically deleted. If an album has been edited (e.g., year, cover, album artist), it will be retained; the same applies to artists.",
          "<span class=\"type-opt\">Navigation Menu Settings Adjustment</span>: Navigation menu settings have been moved to a standalone settings page. Path: <b>Settings</b> -> <b>Navigation Menu</b>"
        ]
      }
    ]
  },
  {
    "version": "0.5.1.0",
    "date": "2026-05-11",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Dynamic Gradient Wallpaper for Playback Interface</span>: You can now set a dynamic gradient wallpaper for the playback interface. Find the <b>Wallpaper</b> option under <b>Settings</b> → <b>UI</b> → <b>Playback Interface</b> to configure it"
        ]
      },
      {
        "type": "opt",
        "items": [
          "Multiple improvements made to<span class=\"type-opt\">the desktop lyrics feature</span>, enhancing stability and display quality",
          "Updated <span class=\"type-opt\">the icons in the sidebar statistics menu</span>."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the popup notification displayed 0 as the song count when adding songs to the playback queue</span>.",
          "Fixed an issue where <span class=\"type-fix\">the outer visual effect of the album cover was being clipped in the playback interface</span>."
        ]
      }
    ]
  },
  {
    "version": "0.4.0.0",
    "date": "2026-05-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Folder drag-and-drop support in the tracks page</span>: You can now drag a folder containing tracks directly from File Explorer onto the tracks page to add the folder and automatically start scanning for tracks.",
          "<span class=\"type-new\">Scan progress dialog</span>: Scan progress is now displayed as a standalone dialog window."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the button spacing in the top-right corner of the playback queue panel was too wide</span>.",
          "Fixed an issue where <span class=\"type-fix\">the text and description of the \"Image Corner Strength\" option did not appear when using English language</span>.",
          "Fixed an issue where <span class=\"type-fix\">text in the plugin management page and its settings page did not update after switching languages</span>."
        ]
      }
    ]
  },
  {
    "version": "0.3.4.0",
    "date": "2026-05-07",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">color extraction from grayscale album covers produced incorrect results</span>.",
          "Fixed a UI issue where <span class=\"type-fix\">text labels on the vertical axis of the statistics chart could overlap</span>.",
          "Fixed an issue where <span class=\"type-fix\">hour tracking in the time period statistics was incorrect</span>."
        ]
      }
    ]
  },
  {
    "version": "0.3.2.0",
    "date": "2026-05-05",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Improved the album cover color extraction algorithm</span>, color results are now more accurate.",
          "<span class=\"type-opt\">Songs already in the queue can now be set as \"Play Next\"</span>, the queue position will be adjusted automatically."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">krc and qrc format lyrics files could not be loaded or parsed correctly</span>."
        ]
      }
    ]
  }
];
