// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[5] = [
  {
    "version": "0.6.0.0",
    "date": "2026-05-16",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "other",
        "items": [
          "Enabled AOT (Ahead-of-Time compilation), <span class=\"type-opt\">significantly improving application performance and startup speed</span>.",
          "Thanks to AOT, the application size has been <span class=\"type-opt\">reduced bymore than 50%</span>."
        ]
      }
    ]
  },
  {
    "version": "0.5.8.0",
    "date": "2026-05-15",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the application failed to start when the settings file was invalid</span>.",
          "Fixed an issue where <span class=\"type-fix\">in some cases the dominant color extracted from a track's cover art was still too close to pure white or pure black</span>."
        ]
      }
    ]
  },
  {
    "version": "0.5.7.0",
    "date": "2026-05-14",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the track information below the cover art was misaligned when the cover art was not square</span>.",
          "Fixed an issue where <span class=\"type-fix\">empty albums (i.e., albums not associated with any tracks) could not be deleted</span>.",
          "Fixed an issue where <span class=\"type-fix\">removing a specific track would incorrectly remove other track</span>.",
          "Fixed an issue where <span class=\"type-fix\">dragging a folder that had already been added onto the track page would cause that folder to be removed</span>.",
          "Fixed an issue where <span class=\"type-fix\">the track count on the right side of the track page title did not update after removing a track</span>."
        ]
      }
    ]
  },
  {
    "version": "0.5.6.0",
    "date": "2026-05-13",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "The dominant color extracted from a track's cover art will now automatically <span class=\"type-opt\">skip colors that are too close to pure black or pure white</span>."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the maximize button displayed incorrectly after entering fullscreen while the window was maximized</span>.",
          "Fixed an issue where <span class=\"type-fix\">the left navigation menu and the right scrollbar were clipped after the window was maximized</span>."
        ]
      }
    ]
  },
  {
    "version": "0.5.5.0",
    "date": "2026-05-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Album Merging Rule Adjustment</span>: A strict artist matching rule has been added. Tracks with the same album name but differing artists will not be merged into the same album.",
          "Updated <span class=\"type-opt\">the icons in the sidebar statistics menu</span>."
        ]
      }
    ]
  }
];
