// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[4] = [
  {
    "version": "0.7.8.0",
    "date": "2026-05-21",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed <span class=\"type-fix\">a crash when playing 16-bit WAV files</span> (thanks to <b>@FunkeymonkeyTTR</b>).",
          "Fixed an issue where <span class=\"type-fix\">the duration of some M4A files was incorrect</span>.",
          "Fixed an issue where <span class=\"type-fix\">some M4A files could not be played</span>.",
          "Fixed an issue where <span class=\"type-fix\">some artists were not displayed on the statistics page</span>."
        ]
      }
    ]
  },
  {
    "version": "0.7.7.0",
    "date": "2026-05-20",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed <span class=\"type-fix\">a crash in the resampling process caused by a buffer write out-of-bounds issue</span> (thanks to <b>@FunkeymonkeyTTR</b>).",
          "Fixed an issue where <span class=\"type-fix\">tracks that no longer existed were displayed incorrectly in the statistics page track list</span>.",
          "Fixed an issue where <span class=\"type-fix\">the menu icon for \"\"Add to next\"\" was displaying incorrectly</span>.",
          "Fixed an issue where <span class=\"type-fix\">generated thumbnails could not be read when the album name or artist name contained characters not supported in filenames</span>."
        ]
      }
    ]
  },
  {
    "version": "0.7.4.0",
    "date": "2026-05-19",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Track cover art now supports searching up to 3 levels of parent folders</span>. When no cover image is found in the track's folder, the player will search upward through parent directories for up to 3 levels"
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">rapidly changing search keywords on the search page could display results from the previous keyword</span>.",
          "Fixed an issue where <span class=\"type-fix\">entering a keyword that would never return any results still displayed all tracks on the search page</span>.",
          "Fixed an issue where <span class=\"type-fix\">the start offset of tracks parsed from CUE files was incorrect in some cases</span>.",
          "Fixed an issue where <span class=\"type-fix\">the duration displayed incorrectly when playing a track corresponding to a CUE file</span>.",
          "Fixed an issue where <span class=\"type-fix\">playing a folder did not include tracks from subfolders</span>."
        ]
      }
    ]
  },
  {
    "version": "0.7.2.0",
    "date": "2026-05-18",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">after switching to shuffle mode, clicking on any track did not play the expected track</span>.",
          "Fixed an issue where <span class=\"type-fix\">m4a files could not be added to the library due to incorrect duration reading</span>.",
          "Fixed an issue where <span class=\"type-fix\">the corner radius of the left button on the bottom playback control panel did not match the corner radius of the track cover thumbnail</span>.",
          "Fixed an issue where <span class=\"type-fix\">Steam plugin settings could not be saved</span>."
        ]
      }
    ]
  },
  {
    "version": "0.7.0.0",
    "date": "2026-05-17",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Track Page Supports Drag-and-Drop</span>: The track page now supports file drag-and-drop. You can drag one or more track files (or folders) onto the page for scanning, no longer limited to folders",
          "<span class=\"type-new\">Playlists Support Drag-and-Drop to Add Tracks</span>: You can now directly drag one or more track files (or folders) onto a playlist. After the drag is complete, tracks will be automatically scanned and added to the playlist"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Dynamic Gradient Effect Adjustment</span>: Removed color mixing to avoid unexpected colors",
          "<span class=\"type-opt\">Window Transparency Effect Adjustment</span>: On Windows 11, Mica effect is used by default; on Windows 10, Acrylic blur is used by default; in other cases, Blur effect is used by default."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the open source licenses page could not be opened</span>.",
          "Fixed an issue where <span class=\"type-fix\">tracks with uppercase file extensions (e.g., .MP3, .FLAC) were not properly recognized</span>."
        ]
      }
    ]
  }
];
