// Auto-generated by tools/split-changelog.js - do not edit. Edit changelog-data.js and re-run the script.
window.CHANGELOG_PAGES = window.CHANGELOG_PAGES || {};
window.CHANGELOG_PAGES[3] = [
  {
    "version": "0.11.0.0",
    "date": "2026-06-12",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Taskbar Playback Control</span>: Hover your mouse over the taskbar icon to access previous track, next track, play, and pause controls — making playback control more convenient.",
          "<span class=\"type-new\">Lyrics Editing</span>: You can now modify and save embedded lyrics for tracks in the track metadata editing dialog."
        ]
      }
    ]
  },
  {
    "version": "0.10.0.0",
    "date": "2026-06-09",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">UI Scale Option</span>: You can now adjust the size of interface elements. Path: <b>Settings -> UI</b>",
          "<span class=\"type-new\">Navigation Bar Expanded Width Setting</span>: You can now adjust the expanded width of the left navigation bar within a range of [100,480]. Path: <b>Settings -> UI</b>",
          "<span class=\"type-new\">New Language Support</span>: Added support for Traditional Chinese, English(UK), Japanese, Korean, Russian, German, French, Portuguese (Brazil), Spanish, Polish, and Turkish. Translations for these languages may contain errors; feedback is welcome."
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Lyric Line Switching</span>: Added fade-in/fade-out effect.",
          "<span class=\"type-opt\">Lyrics Font Size and Weight Adjustment</span>: Normal and highlighted lyric text now use the same font size and weight."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">artists could not be dragged in the album edit dialog</span>.",
          "Fixed <span class=\"type-fix\">a potential crash when right-clicking on the album page</span>.",
          "Fixed an issue where <span class=\"type-fix\">the close button became unresponsive after closing the window and reopening it via the taskbar button</span>.",
          "Fixed an issue where <span class=\"type-fix\">the default icon was not shown when a track had no cover</span>.",
          "Fixed an issue where <span class=\"type-fix\">the end of a track was being truncated</span>.",
          "Fixed an issue where <span class=\"type-fix\">auto-scrolling after clicking a track in the playback queue caused the currently playing track to become invisible</span>.",
          "Fixed an issue where <span class=\"type-fix\">the previous track's cover and lyrics were still displayed when a track file failed to load</span>.",
          "Fixed an issue where <span class=\"type-fix\">existing lyrics were lost when saving track metadata</span>."
        ]
      }
    ]
  },
  {
    "version": "0.9.0.0",
    "date": "2026-06-05",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Track Metadata Editing</span>: Supports modifying track cover, title, artist, and year. Changes to track metadata will be written to the track file by default. Note that editing metadata for tracks from CUE files is currently not supported. Path: Right-click a track -> Select <b>Edit Metadata</b>",
          "<span class=\"type-new\">Album Metadata Editing</span>: Supports modifying album title, artist, and year. You can choose to apply album title, artist, year, and cover to all tracks in the album (will be written to corresponding track files). Note that editing album metadata is not supported when the album contains tracks from CUE files. Path: Right-click an album -> Select <b>Edit Metadata</b>",
          "<span class=\"type-new\">Full Scan Option</span>: When enabled, rescans all tracks to ensure track data is up to date. Path: <b>Settings -> Library -> Full scan</b>"
        ]
      },
      {
        "type": "opt",
        "items": [
          "<span class=\"type-opt\">Included Folders</span>: When adding a new folder, if any subfolders of that folder already exist in the list, those subfolders are automatically removed.",
          "<span class=\"type-opt\">CUE File Parsing</span>: Removes possible double quotes attached to the genre field.",
          "<span class=\"type-opt\">Page Navigation</span>: After clicking a folder on the folder page, the page indicator stays on the folder menu instead of switching to the track menu; similar adjustments have been made for the playlist page.",
          "<span class=\"type-opt\">Thumbnail Generation</span>: Generates thumbnails with a uniform height of 200 pixels. No longer generates different thumbnail sizes for tracks, albums, and artists, reducing disk space usage.",
          "<span class=\"type-opt\">Artist/Genre Parsing</span>: Intelligently recognizes and preserves manually modified track artist, album artist, and genre information, preventing them from being overwritten by original tags."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the Add Playlist dialog was too small</span>.",
          "Fixed <span class=\"type-fix\">a potential crash when right-clicking on the album page</span>.",
          "Fixed an issue where <span class=\"type-fix\">clicking the \"Library\" button on the track page with no tracks present would incorrectly select the \"Settings\" menu after navigating</span>.",
          "Fixed an issue where <span class=\"type-fix\">saving after deleting an artist while editing album metadata would incorrectly delete that artist</span>.",
          "Fixed an issue where <span class=\"type-fix\">rescanning failed to update track information after modifying track metadata externally</span>.",
          "Fixed an issue where <span class=\"type-fix\">in some cases, audio files associated with CUE files were incorrectly added to the library as regular track files</span>.",
          "Fixed an issue where <span class=\"type-fix\">edited albums or artists could not be removed even when they met the removal conditions</span>.",
          "Fixed an issue where <span class=\"type-fix\">incorrect scan results were displayed after dragging folders or multiple track files onto the track or playlist page</span>.",
          "Fixed an issue where <span class=\"type-fix\">view settings were not correctly applied when switching to the album page for the first time</span>."
        ]
      }
    ]
  },
  {
    "version": "0.8.1.0",
    "date": "2026-05-24",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "opt",
        "items": [
          "<span class=\"type-new\">Mini Window Playlist Operations</span>: Added a playlist operation page for the mini window. Click the playlist button in the bottom-right corner to open it. Supports switching tracks, removing tracks from the queue, clearing the queue, and more.",
          "<span class=\"type-new\">Mini Window Settings</span>: Added a settings page for the mini window. Click the settings button on the far right to open it. Currently includes the following settings: theme (synced with global settings), overlay opacity, and whether to show the mini window icon in the taskbar.",
          "<span class=\"type-new\">Removed Corner Radius from Mini Window Track Cover</span>: Removed the corner radius effect from the track cover in the mini window to avoid black or white areas appearing at the window corners.",
          "<span class=\"type-new\">Default Value Adjustment for Duration Filter</span>: The default value for the duration filter setting has been adjusted to 0 to avoid affecting scan results when scanning tracks for the first time."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">content overflowed on the album details page when the description text was too long</span>.",
          "Fixed an issue where <span class=\"type-fix\">content overflowed and the page could not scroll on the artist details page when the description text was too long</span>.",
          "Fixed an issue where <span class=\"type-fix\">an image could not be set for an artist when the artist name contained special characters</span>."
        ]
      }
    ]
  },
  {
    "version": "0.8.0.0",
    "date": "2026-05-22",
    "tag": "Alpha",
    "tagClass": "tag-alpha",
    "categories": [
      {
        "type": "new",
        "items": [
          "<span class=\"type-new\">Rendering Mode Option</span>: When experiencing rendering issues such as flickering or display problems, you can try switching the rendering mode. Path: <b>Settings -> UI -> Rendering mode</b>.",
          "<span class=\"type-new\">Automatic Log File Cleanup</span>: The application will automatically delete log files older than 7 days on startup. Additionally, you can click <b>Clear Cache</b> under <b>Log Cache</b> on the <b>About page</b> to delete all log files at any time."
        ]
      },
      {
        "type": "fix",
        "items": [
          "Fixed an issue where <span class=\"type-fix\">the application failed to start when the settings file was invalid</span>."
        ]
      }
    ]
  }
];
